### ISSUE TITLE
Requests are not scoped to the current repo

### ISSUE THREAD

**Issue by ramnes** [BloopAI/bloop#334]
Hey there, thanks for the neat tool! Discussed that exact idea a few days ago with a friend, happy to see such a tool already live.

**Describe the bug**
Requests are not scoped to the current repo.

**Expected behavior**
When I click on a repo and ask a question, I expect the answers to only consider the current repository, not other repositories I may have sychronized.

**To Reproduce**
- Click on a repo.
- Ask a question.
- See code from another repo.

**Additional context**
- Using latest macOS bloop build available (v0.3.1)
- Using both local (2x) and GitHub (1x) repositories.

**Comment by ggordonhall** [comment]
Hey @ramnes, thanks for raising this. This is something we're aware of and are working to address. We're working on some improvements to the `rephrase` prompt (which outputs the semantic search query), so that it can generate queries constrained by repo (e.g. `OAuth test repo:bloop`) if that makes sense given the conversational context.

If you have any ideas on how this can be improved please share!

**Comment by ramnes** [comment]
Cool. Adding `repo:` manually to each query works, would be a quick and easy fix if bloop could do this for me. :)

**Comment by ggordonhall** [comment]
This has been implemented in **v0.3.4**: https://github.com/BloopAI/bloop/releases/tag/v0.3.4
