### ISSUE TITLE
Can't show github device Code in windows 11

### ISSUE THREAD

**Issue by SamPeng87** [BloopAI/bloop#673]
**Describe the bug**
lauch bloopai desktop，need connect github。but，can't show any device code in screen。

**Expected behavior**
show github device code

**To Reproduce**

**Screenshots or output**
If applicable, add screenshots to help illustrate the bug.

**Additional context**
version is latest 0.4.5

**Comment by HiChen404** [comment]
+1

**Comment by agawrylak** [comment]
Same here

**Comment by vicdotexe** [comment]
I'm windows 10 and getting the same. no device code, and launch github login just opens my file explorer.

**Comment by donghquinn** [comment]
Same here mac os Ventura

**Comment by calyptobai** [comment]
Thanks for the report @SamPeng87! Can you check if this is still an issue on `0.4.13`?

**Comment by worldofgeese** [comment]
I don't think is OS-specific: I have `v0.4.14` on Linux and there's no device code given.

**Comment by donghquinn** [comment]
I'm using Mac OS and still got no github auth code yet.

2023년 8월 15일 (화) 오후 10:27, calyptobai ***@***.***>님이 작성:

**Comment by ggordonhall** [comment]
The GitHub device code isn't shown because the bloop server (`bleep`) has failed to start. There could be many causes of this, but one that we've seen before is that there's a Qdrant process already running when you launch the bloop app. Can you check to see if Qdrant is already running?

We also store debug logs which should help pin this down (depending on OS):
- `~/Library/Application\ Support/ai.bloop.bloop/bleep/logs`
- `%APPDATA%/bloop/bleep/logs`
- `~/.local/share/bloop/bleep/logs`
